name: PR checker

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]

jobs:
  pr-checker:
    name: Check PR description
    runs-on: [ubuntu-latest]
    steps:
      - name: Run PR title check
        uses: transferwise/actions-pr-checker@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE_CONTAINS_PATTERN: ".{15,}" # Require at least 10 characters in the title
          PR_COMMENT: |
            Please provide a more meaningful PR title with at least 15 characters.

      - name: Run PR description check
        uses: transferwise/actions-pr-checker@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_CONTAINS_PATTERN: ".{25,}" # Require at least 10 characters in the description
          PR_COMMENT: |
            Please provide a more meaningful PR description with at least 25 characters.
